server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: test
      port: 27017
      
  eureka:
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: circuitbreakers,circuitbreakerevents,health,info,ratelimiters,metrics
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            subscription:
                allowHealthIndicatorToFail: false
                automaticTransitionFromOpenToHalfOpenEnabled: true
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 5
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: 15000
    retry:
        instances:
            subscription:
                maxAttempts: 3
                retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
                waitDuration: 1000
